### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by JuliMPH** [xia-lab/MetaboAnalystR#187]
I cannot manage to install the MetaboAnalystR package. After installing Rtools and all the dependencies succesfully, I get the following error when trying to install MetaboAnalystR:

ERROR: dependency 'SSPA' is not available for package 'MetaboAnalystR'

However, SSPA does seem to be installed:

The downloaded source packages are in
	‘C:\Users\Metabolomics\AppData\Local\Temp\RtmpCmvohl\downloaded_packages’
[1] "Rgraphviz"          "SSPA"               "KEGGgraph"          " packages added..."

You can find below the full output I get (including the error) when I try to install the package:

> library(devtools)
Loading required package: usethis
> 
> devtools::install_github("xia-lab/MetaboAnalystR", build = TRUE, build_vignettes = FALSE)
Downloading GitHub repo xia-lab/MetaboAnalystR@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                               
2: CRAN packages only                
3: None                              
4: colorspace (2.0-1 -> 2.0-2) [CRAN]
5: dplyr      (1.0.6 -> 1.0.7) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 
√  checking for file 'C:\Users\Metabolomics\AppData\Local\Temp\RtmpCmvohl\remotes2a386aea7084\xia-lab-MetaboAnalystR-173b858/DESCRIPTION' ... 
-  preparing 'MetaboAnalystR': (4.2s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (1s)
-  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
-  building 'MetaboAnalystR_3.0.3.tar.gz'
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     'MetaboAnalystR/vignettes/MetaboAnalystR_3_workflow_Towards_Optimized_Workflow_for_Global_Metabolomics.Rmd'
   
Installing package into ‘C:/Users/Metabolomics/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
ERROR: dependency 'SSPA' is not available for package 'MetaboAnalystR'
* removing 'C:/Users/Metabolomics/Documents/R/win-library/4.1/MetaboAnalystR'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/METABO~1/AppData/Local/Temp/RtmpCmvohl/file2a3865b134e2/MetaboAnalystR_3.0.3.tar.gz’ had non-zero exit status

**Comment by MoOhu** [comment]
Hi,
I have a similar issue. I can't install MetaboAnalystR because of SSPA.
The problem seems to be, that the package SSPA is deprecated on Bioconductor 3.13 (https://bioconductor.org/packages/release/bioc/html/SSPA.html).

This is what I did:

I installed all dependencies for linux and used the metanr_packages() function to install the R-package dependencies.
All packages could be installed except for SPAA: 

> metr_pkgs <- c("impute", "pcaMethods", "globaltest", "GlobalAncova", "Rgraphviz", "preprocessCore", "genefilter", "SSPA", "sva", "limma", "KEGGgraph", "siggenes","BiocParallel", "MSnbase", "multtest","RBGL","edgeR","fgsea","devtools","crmn","httr","qs")
> 
> list_installed <- installed.packages()
> 
> new_pkgs <- subset(metr_pkgs, !(metr_pkgs %in% list_installed[, "Package"]))
> new_pkgs
[1] "SSPA"

If I try to install SSPA, I get the following error messages:
> if (!requireNamespace("BiocManager", quietly = TRUE))
> 	install.packages("BiocManager")
> 
> BiocManager::install("SSPA")

Bioconductor version 3.13 (BiocManager 1.30.16), R 4.1.0 (2021-05-18)
Installing package(s) 'SSPA'
Installation paths not writeable, unable to update packages
  path: /usr/lib/R/library
  packages:
    spatial
Warning message:
In .inet_warning(msg) :
  package ‘SSPA’ is not available for Bioconductor version '3.13'

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

─ Session info ─────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.1.0 (2021-05-18)
 os       Linux Mint 20               
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language en_US                       
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Vienna               
 date     2021-07-01                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 BiocManager   1.30.16 2021-06-15 [1] CRAN (R 4.1.0)
 cachem        1.0.5   2021-05-15 [1] CRAN (R 4.1.0)
 callr         3.7.0   2021-04-20 [1] CRAN (R 4.1.0)
 cli           3.0.0   2021-06-30 [1] CRAN (R 4.1.0)
 crayon        1.4.1   2021-02-08 [1] CRAN (R 4.1.0)
 curl          4.3.2   2021-06-23 [1] CRAN (R 4.1.0)
 desc          1.3.0   2021-03-05 [1] CRAN (R 4.1.0)
 devtools    * 2.4.2   2021-06-07 [1] CRAN (R 4.1.0)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.1.0)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.1.0)
 fs            1.5.0   2020-07-31 [1] CRAN (R 4.1.0)
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.1.0)
 lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.1.0)
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.1.0)
 memoise       2.0.0   2021-01-26 [1] CRAN (R 4.1.0)
 pkgbuild      1.2.0   2020-12-15 [1] CRAN (R 4.1.0)
 pkgload       1.2.1   2021-04-06 [1] CRAN (R 4.1.0)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.1.0)
 processx      3.5.2   2021-04-30 [1] CRAN (R 4.1.0)
 ps            1.6.0   2021-02-28 [1] CRAN (R 4.1.0)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.1.0)
 R6            2.5.0   2020-10-28 [1] CRAN (R 4.1.0)
 remotes       2.4.0   2021-06-02 [1] CRAN (R 4.1.0)
 rlang         0.4.11  2021-04-30 [1] CRAN (R 4.1.0)
 rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.1.0)
 rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.1.0)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.1.0)
 testthat      3.0.4   2021-07-01 [1] CRAN (R 4.1.0)
 usethis     * 2.0.1   2021-02-10 [1] CRAN (R 4.1.0)
 withr         2.4.2   2021-04-18 [1] CRAN (R 4.1.0)

[1] /home/xxx/R/x86_64-pc-linux-gnu-library/4.1
[2] /usr/local/lib/R/site-library
[3] /usr/lib/R/site-library
[4] /usr/lib/R/library

**Comment by pstew** [comment]
Had this same issue. I solved it by cloning the SSPA package directly from Bioconductor (git command at the bottom of the SSPA page). I then installed locally with `install.packages("path/to/library", repos = NULL, type="source")` . Their DESCRIPTION file had `'zzz.R'` duplicated in the Collate: section (line 17), so after deleting the extra copy it installed. MetaboAnalystR then installed fine (after also manually installing glasso, which seems to be a dependency that did not get auto-installed). Hope this helps.

**Comment by MoOhu** [comment]
Thank you very much, everything worked out with your description.

**Comment by biryb** [comment]
I am also unable to install this dependency. I followed pstew's advice from 19072021 but the git link is broken. I found version 1.6.0 as a .tgz and attempted to install this via 

> install.packages("path/Downloads/SSPA", repos = NULL, type="source")
* installing *binary* package ‘SSPA’ ...
* DONE (SSPA)
> library(SSPA)
Error: package ‘SSPA’ was built before R 3.0.0: please re-install it

I'm running R 4.2.2 and on MetaboAnalystR it says that R > 4.0 is required. Is this package no longer required for MetaboAnalystR?

**Comment by Xueyao0830** [comment]
> Installing "SSPA" directly from the github repository worked for me: `devtools::install_github("https://github.com/mvaniterson/SSPA")`

I still have this issue...
I also git clone the original SSPA repository, and cannot install it, do you guys know how to solve this issue?

> devtools::install_github("mvaniterson/SSPA")
Using GitHub PAT from the git credential store.
Downloading GitHub repo mvaniterson/SSPA@HEAD
Error: Failed to install 'SSPA' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

**Comment by Nesln** [comment]
> Could not find tools necessary to compile a package

Rtools is needed if compiling a package

You can download & install Rtools from this link:
https://cran.r-project.org/bin/windows/Rtools/

**Comment by KyleWillisWarwickUniversity** [comment]
> I am also unable to install this dependency. I followed pstew's advice from 19072021 but the git link is broken. I found version 1.6.0 as a .tgz and attempted to install this via
> 
> > install.packages("path/Downloads/SSPA", repos = NULL, type="source")
> 
> * installing _binary_ package ‘SSPA’ ...
> * DONE (SSPA)
> 
> > library(SSPA)
> > Error: package ‘SSPA’ was built before R 3.0.0: please re-install it
> 
> I'm running R 4.2.2 and on MetaboAnalystR it says that R > 4.0 is required. Is this package no longer required for MetaboAnalystR?
> 
> Many thanks!

Did you manage to sort this issue I also have the same error message
