### ISSUE TITLE
Importing more than two groups of raw ms data 

### ISSUE THREAD

**Issue by FOO-95** [xia-lab/MetaboAnalystR#47]
I just started using the MetaboAnalystR package and have been experiencing issues importing my data. I have 4 groups of samples, each with 8 NetCDF LC/MS files and this error always comes up: Error in plot.xy(xy.coords(x, y), type = type, ...) : invalid color name 'NA60'
Is the ImportRawMSData function only limited to 2 groups? I ask this because I  was able to import 2 of my 4 groups successfully, but I couldn't import all four groups. Is there a function for more than two groups? Any advice would be greatly appreciated.

**Comment by jsychong** [comment]
Hi, the ImportRawMSData is definitely able to accept >2 groups. To clarify, the error directly appears when running that function?

**Comment by FOO-95** [comment]
So once I run the function, it immediately says the number of cpu cores to be used. After a few minutes the error message comes up.

**Comment by jsychong** [comment]
Thanks for letting us know about this error. I believe I've fixed it, please re-install the package and let me know if it worked out!

**Comment by FOO-95** [comment]
Hi, so I did as you instructed but unfortunately, the data is still not being imported and the error keeps coming up. The number of levels (groups) in the files is acknowledged and this time a BPIS plot is produced (incomplete with no legend). Is there perhaps a file size limit? I downloaded the package using the option C method in the download instructions (Manual download of MetaboAnalystR_2.0.0.tar.gz and install locally), could this be an issue? Any advice would be helpful.

**Comment by jsychong** [comment]
It seems like plotting could be the issue for some reason. I set this to be a TRUE/FALSE parameter so if you re-install the R package, but using Option A/B (GitHub hosts the most up to date release), and use ImportRawMSData (foldername, format = "png", dpi = 72, width = 9,  par.cores=TRUE, plot=FALSE) it should work now.

**Comment by FOO-95** [comment]
I have tried it and it works now. Thank you for the help.
